services:
  gobackup:
    image: huacnlee/gobackup:v2.12.0
    volumes:
      - xxxx:/data/
      - ./_data:/etc/gobackup
      - ./gobackup.yaml:/etc/gobackup/gobackup.yml
    ports:
      - 2703:2703
    command: ["gobackup", "perform"]
