services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      - TZ:Asia/Shanghai
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "11201:3306"
    volumes:
      - ./_data:/var/lib/mysql

