services:
  mysql:
    image: mysql:8 # or 5.7
    restart: always
    environment:
      - TZ:Asia/Shanghai
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - ./_data:/var/lib/mysql
